/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kodfarki.subscreasy.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kodfarki.subscreasy.client.model.Company;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CompanyProps
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-30T00:20:36.956+03:00")
public class CompanyProps {
  @SerializedName("apiKey")
  private String apiKey = null;

  @SerializedName("callbackUrl")
  private String callbackUrl = null;

  @SerializedName("company")
  private Company company = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("paymentGatewayApiKey")
  private String paymentGatewayApiKey = null;

  @SerializedName("paymentGatewaySecurityKey")
  private String paymentGatewaySecurityKey = null;

  /**
   * Gets or Sets paymentMethod
   */
  @JsonAdapter(PaymentMethodEnum.Adapter.class)
  public enum PaymentMethodEnum {
    OFFLINE("OFFLINE"),
    
    IYZICO("IYZICO"),
    
    PAYU("PAYU");

    private String value;

    PaymentMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PaymentMethodEnum fromValue(String text) {
      for (PaymentMethodEnum b : PaymentMethodEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PaymentMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PaymentMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PaymentMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PaymentMethodEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("paymentMethod")
  private PaymentMethodEnum paymentMethod = null;

  @SerializedName("secureKey")
  private String secureKey = null;

  public CompanyProps apiKey(String apiKey) {
    this.apiKey = apiKey;
    return this;
  }

   /**
   * Get apiKey
   * @return apiKey
  **/
  @ApiModelProperty(value = "")
  public String getApiKey() {
    return apiKey;
  }

  public void setApiKey(String apiKey) {
    this.apiKey = apiKey;
  }

  public CompanyProps callbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
    return this;
  }

   /**
   * Get callbackUrl
   * @return callbackUrl
  **/
  @ApiModelProperty(value = "")
  public String getCallbackUrl() {
    return callbackUrl;
  }

  public void setCallbackUrl(String callbackUrl) {
    this.callbackUrl = callbackUrl;
  }

  public CompanyProps company(Company company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @ApiModelProperty(value = "")
  public Company getCompany() {
    return company;
  }

  public void setCompany(Company company) {
    this.company = company;
  }

  public CompanyProps id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public CompanyProps paymentGatewayApiKey(String paymentGatewayApiKey) {
    this.paymentGatewayApiKey = paymentGatewayApiKey;
    return this;
  }

   /**
   * Get paymentGatewayApiKey
   * @return paymentGatewayApiKey
  **/
  @ApiModelProperty(value = "")
  public String getPaymentGatewayApiKey() {
    return paymentGatewayApiKey;
  }

  public void setPaymentGatewayApiKey(String paymentGatewayApiKey) {
    this.paymentGatewayApiKey = paymentGatewayApiKey;
  }

  public CompanyProps paymentGatewaySecurityKey(String paymentGatewaySecurityKey) {
    this.paymentGatewaySecurityKey = paymentGatewaySecurityKey;
    return this;
  }

   /**
   * Get paymentGatewaySecurityKey
   * @return paymentGatewaySecurityKey
  **/
  @ApiModelProperty(value = "")
  public String getPaymentGatewaySecurityKey() {
    return paymentGatewaySecurityKey;
  }

  public void setPaymentGatewaySecurityKey(String paymentGatewaySecurityKey) {
    this.paymentGatewaySecurityKey = paymentGatewaySecurityKey;
  }

  public CompanyProps paymentMethod(PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @ApiModelProperty(value = "")
  public PaymentMethodEnum getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public CompanyProps secureKey(String secureKey) {
    this.secureKey = secureKey;
    return this;
  }

   /**
   * Get secureKey
   * @return secureKey
  **/
  @ApiModelProperty(value = "")
  public String getSecureKey() {
    return secureKey;
  }

  public void setSecureKey(String secureKey) {
    this.secureKey = secureKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyProps companyProps = (CompanyProps) o;
    return Objects.equals(this.apiKey, companyProps.apiKey) &&
        Objects.equals(this.callbackUrl, companyProps.callbackUrl) &&
        Objects.equals(this.company, companyProps.company) &&
        Objects.equals(this.id, companyProps.id) &&
        Objects.equals(this.paymentGatewayApiKey, companyProps.paymentGatewayApiKey) &&
        Objects.equals(this.paymentGatewaySecurityKey, companyProps.paymentGatewaySecurityKey) &&
        Objects.equals(this.paymentMethod, companyProps.paymentMethod) &&
        Objects.equals(this.secureKey, companyProps.secureKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiKey, callbackUrl, company, id, paymentGatewayApiKey, paymentGatewaySecurityKey, paymentMethod, secureKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyProps {\n");
    
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    callbackUrl: ").append(toIndentedString(callbackUrl)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    paymentGatewayApiKey: ").append(toIndentedString(paymentGatewayApiKey)).append("\n");
    sb.append("    paymentGatewaySecurityKey: ").append(toIndentedString(paymentGatewaySecurityKey)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    secureKey: ").append(toIndentedString(secureKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

