/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kodfarki.subscreasy.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.kodfarki.subscreasy.client.model.ChargingLog;
import com.kodfarki.subscreasy.client.model.SavedCard;
import com.kodfarki.subscreasy.client.model.Subscriber;
import com.kodfarki.subscreasy.client.model.Subsription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * WebHookRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-19T15:02:48.500+03:00")
public class WebHookRequest {
  @SerializedName("paymentLog")
  private ChargingLog paymentLog = null;

  @SerializedName("savedCard")
  private SavedCard savedCard = null;

  @SerializedName("subscriber")
  private Subscriber subscriber = null;

  @SerializedName("subscription")
  private Subsription subscription = null;

  @SerializedName("txId")
  private String txId = null;

  public WebHookRequest paymentLog(ChargingLog paymentLog) {
    this.paymentLog = paymentLog;
    return this;
  }

   /**
   * Get paymentLog
   * @return paymentLog
  **/
  @ApiModelProperty(value = "")
  public ChargingLog getPaymentLog() {
    return paymentLog;
  }

  public void setPaymentLog(ChargingLog paymentLog) {
    this.paymentLog = paymentLog;
  }

  public WebHookRequest savedCard(SavedCard savedCard) {
    this.savedCard = savedCard;
    return this;
  }

   /**
   * Get savedCard
   * @return savedCard
  **/
  @ApiModelProperty(value = "")
  public SavedCard getSavedCard() {
    return savedCard;
  }

  public void setSavedCard(SavedCard savedCard) {
    this.savedCard = savedCard;
  }

  public WebHookRequest subscriber(Subscriber subscriber) {
    this.subscriber = subscriber;
    return this;
  }

   /**
   * Get subscriber
   * @return subscriber
  **/
  @ApiModelProperty(value = "")
  public Subscriber getSubscriber() {
    return subscriber;
  }

  public void setSubscriber(Subscriber subscriber) {
    this.subscriber = subscriber;
  }

  public WebHookRequest subscription(Subsription subscription) {
    this.subscription = subscription;
    return this;
  }

   /**
   * Get subscription
   * @return subscription
  **/
  @ApiModelProperty(value = "")
  public Subsription getSubscription() {
    return subscription;
  }

  public void setSubscription(Subsription subscription) {
    this.subscription = subscription;
  }

  public WebHookRequest txId(String txId) {
    this.txId = txId;
    return this;
  }

   /**
   * Get txId
   * @return txId
  **/
  @ApiModelProperty(value = "")
  public String getTxId() {
    return txId;
  }

  public void setTxId(String txId) {
    this.txId = txId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebHookRequest webHookRequest = (WebHookRequest) o;
    return Objects.equals(this.paymentLog, webHookRequest.paymentLog) &&
        Objects.equals(this.savedCard, webHookRequest.savedCard) &&
        Objects.equals(this.subscriber, webHookRequest.subscriber) &&
        Objects.equals(this.subscription, webHookRequest.subscription) &&
        Objects.equals(this.txId, webHookRequest.txId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentLog, savedCard, subscriber, subscription, txId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebHookRequest {\n");
    
    sb.append("    paymentLog: ").append(toIndentedString(paymentLog)).append("\n");
    sb.append("    savedCard: ").append(toIndentedString(savedCard)).append("\n");
    sb.append("    subscriber: ").append(toIndentedString(subscriber)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("    txId: ").append(toIndentedString(txId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

