/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kodfarki.subscreasy.client;

import com.kodfarki.subscreasy.ApiException;
import com.kodfarki.subscreasy.client.model.Invoice;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InvoiceResourceApi
 */
@Ignore
public class InvoiceResourceApiTest {

    private final InvoiceResourceApi api = new InvoiceResourceApi();

    
    /**
     * createInvoice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createInvoiceUsingPOSTTest() throws ApiException {
        Invoice invoice = null;
        Invoice response = api.createInvoiceUsingPOST(invoice);

        // TODO: test validations
    }
    
    /**
     * deleteInvoice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteInvoiceUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteInvoiceUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * getAllInvoices
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllInvoicesUsingGETTest() throws ApiException {
        List<Invoice> response = api.getAllInvoicesUsingGET();

        // TODO: test validations
    }
    
    /**
     * getInvoiceBySubscriber
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInvoiceBySubscriberUsingGETTest() throws ApiException {
        String subscriberSecureId = null;
        List<Invoice> response = api.getInvoiceBySubscriberUsingGET(subscriberSecureId);

        // TODO: test validations
    }
    
    /**
     * getInvoice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getInvoiceUsingGETTest() throws ApiException {
        Long id = null;
        Invoice response = api.getInvoiceUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * updateInvoice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateInvoiceUsingPUTTest() throws ApiException {
        Invoice invoice = null;
        Invoice response = api.updateInvoiceUsingPUT(invoice);

        // TODO: test validations
    }
    
}
