/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kodfarki.subscreasy.client;

import com.kodfarki.subscreasy.ApiException;
import com.kodfarki.subscreasy.client.model.OrderItem;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrderItemResourceApi
 */
@Ignore
public class OrderItemResourceApiTest {

    private final OrderItemResourceApi api = new OrderItemResourceApi();

    
    /**
     * createOrderItem
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createOrderItemUsingPOSTTest() throws ApiException {
        OrderItem orderItem = null;
        OrderItem response = api.createOrderItemUsingPOST(orderItem);

        // TODO: test validations
    }
    
    /**
     * deleteOrderItem
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteOrderItemUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteOrderItemUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * getAllOrderItems
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllOrderItemsUsingGETTest() throws ApiException {
        List<OrderItem> response = api.getAllOrderItemsUsingGET();

        // TODO: test validations
    }
    
    /**
     * getOrderItem
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOrderItemUsingGETTest() throws ApiException {
        Long id = null;
        OrderItem response = api.getOrderItemUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * updateOrderItem
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateOrderItemUsingPUTTest() throws ApiException {
        OrderItem orderItem = null;
        OrderItem response = api.updateOrderItemUsingPUT(orderItem);

        // TODO: test validations
    }
    
}
