/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.kodfarki.subscreasy.client;

import com.kodfarki.subscreasy.ApiException;
import com.kodfarki.subscreasy.client.model.ProfileInfoVM;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProfileInfoResourceApi
 */
@Ignore
public class ProfileInfoResourceApiTest {

    private final ProfileInfoResourceApi api = new ProfileInfoResourceApi();

    
    /**
     * getActiveProfiles
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getActiveProfilesUsingGETTest() throws ApiException {
        ProfileInfoVM response = api.getActiveProfilesUsingGET();

        // TODO: test validations
    }
    
}
